title: FP Launchpad
email: contact@fplaunchpad.org
description: Centre for Functional Systems Research and Education at IIT Madras
baseurl: ""
url: "https://fplaunchpad.org"
logo: /assets/images/logo-400.png

# Build settings
markdown: kramdown
kramdown:
  auto_ids: true
theme: minima

# Navigation
header_pages:
  - index.md
  - charter.md

# Social links (optional - add as needed)
# github_username: prismlab
# twitter_username:

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
